Repository soundise/react-components, pull requests merged in 2023-01, with the labels that each got.

#11 chore: v1.1.0 release
  package.json
Labels: release

#20 fix: yarn warnings
  README.md
  package.json
  yarn.lock
Labels: dependencies

#21 fix: styled esm import
  .eslintrc
  jest.config.ts
  src/globalStyle/GlobalStyle.tsx
  src/soundiseIcon/SoundiseIcon.tsx
  src/soundiseLogo/SoundiseLogo.tsx
  src/styledComponents.ts
  tsconfig.json
Labels: bug

#22 feat: theme color shades
  src/styledComponents.ts
  src/theme/__snapshots__/theme.test.ts.snap
  src/theme/colors/green.ts
  src/theme/colors/index.ts
  src/theme/colors/red.ts
  src/theme/colors/yellow.ts
  src/theme/darkTheme.ts
  src/theme/index.ts
  src/theme/lightTheme.ts
  src/theme/theme.ts
Labels: enhancement

#24 chore: v1.1.1 release
  package.json
Labels: release

#25 chore: refactoring
  .eslintrc
  jest.config.ts
  package.json
  src/globalStyle/GlobalStyle.tsx
  src/soundiseIcon/SoundiseIcon.test.tsx
  src/soundiseIcon/SoundiseIcon.tsx
  src/soundiseIcon/__snapshots__/SoundiseIcon.test.tsx.snap
  src/soundiseLogo/SoundiseLogo.test.tsx
  src/soundiseLogo/SoundiseLogo.tsx
  src/soundiseLogo/__snapshots__/SoundiseLogo.test.tsx.snap
  src/styledComponents.ts
  src/theme/__snapshots__/theme.test.ts.snap
  src/theme/lightTheme.ts
  yarn.lock
Labels: bug, enhancement

#26 chore: v1.1.2 release
  package.json
Labels: release

#27 feat: soundise app icon
  src/index.ts
  src/soundiseAppIcon/SoundiseAppIcon.test.tsx
  src/soundiseAppIcon/SoundiseAppIcon.tsx
  src/soundiseAppIcon/__snapshots__/SoundiseAppIcon.test.tsx.snap
  src/soundiseAppIcon/index.ts
Labels: enhancement

#28 chore: better global style
  src/globalStyle/GlobalStyle.tsx
Labels: enhancement

#29 chore: v1.2.0 release
  package.json
Labels: release

#30 feat: storybook
  .eslintignore
  .eslintrc
  .github/workflows/build-test.yml
  .github/workflows/generate-version.yml
  .github/workflows/lint.yml
  .github/workflows/publish-package.yml
  .gitignore
  .prettierignore
  .storybook/main.ts
  .storybook/manager-head.html
  .storybook/manager.ts
  .storybook/preview-body.html
  .storybook/preview-head.html
  .storybook/preview.tsx
  .storybook/public/manifest.json
  .storybook/themes/index.ts
  .storybook/themes/soundiseDark.ts
  .storybook/themes/soundiseLight.ts
  .storybook/utils/index.ts
  .storybook/utils/isDarkMode.ts
  README.md
  jest.config.ts
  package.json
  src/globalStyle/GlobalStyle.tsx
  src/soundiseAppIcon/SoundiseAppIcon.stories.tsx
  src/soundiseAppIcon/SoundiseAppIcon.test.tsx
  src/soundiseAppIcon/SoundiseAppIcon.tsx
  src/soundiseAppIcon/__snapshots__/SoundiseAppIcon.test.tsx.snap
  src/soundiseIcon/SoundiseIcon.stories.tsx
  src/soundiseIcon/SoundiseIcon.test.tsx
  src/soundiseIcon/SoundiseIcon.tsx
  src/soundiseIcon/__snapshots__/SoundiseIcon.test.tsx.snap
  src/soundiseLogo/SoundiseLogo.stories.tsx
  src/soundiseLogo/SoundiseLogo.test.tsx
  src/soundiseLogo/SoundiseLogo.tsx
  src/soundiseLogo/__snapshots__/SoundiseLogo.test.tsx.snap
  src/theme/__snapshots__/theme.test.ts.snap
  src/theme/breakpoints/breakpoints.ts
  src/theme/darkTheme.ts
  src/theme/lightTheme.ts
  src/theme/theme.ts
  src/theme/typography/fonts.ts
  src/theme/typography/weights.ts
  stories/Introduction.mdx
  tsconfig.json
  yarn.lock
Labels: enhancement

#32 chore: v2.0.0 release
  package.json
Labels: release
